### ISSUE TITLE
SEO / Server rendering does not work

### ISSUE THREAD

**Issue by vschettino** [barancezayirli/gatsby-starter-resume-cms#1]
Hi Baran,

Do you know why head metatags, title, etc are not rendered server side on your starter? 

You can see it using tools like [twitter card validator](https://cards-dev.twitter.com/validator). I [thougth](https://www.gatsbyjs.org/docs/seo/#server-rendering) it could be something related to `gatsby-plugin-offline` but I removed it using their uninstall instructions and it still does not work. 
Can you please help?

**Comment by barancezayirli** [comment]
@vschettino sorry for the really late response, I was a bit busy these days and couldn't have chance to check though when I check with the published version twitter card validator detects 5 metatags
